### ISSUE TITLE
Is it okay for Omnibox clone?

### ISSUE THREAD

**Issue by nocaoper** [taicki/omnibox-timer#16]
Hello taicki, 

I had published a timerfix version on google chrome since a bit and am wondering if it is okay with you. If there are any problems with it or if you would like for me to delete it I will be happy to as recommended.

Cheers,
Yu

**Comment by nocaoper** [comment]
In any case, your plugin has been akin to life-changing for me. Thank you!

**Comment by taicki** [comment]
I could not maintain omnibox-timer for a while, but now got some time! If you create a pull request for your fixes, I will review and merge them. 🙇

**Comment by nocaoper** [comment]
Hurray!!
